name: "visual_changenet_segmentation_tao"
platform: "tensorrt_plan"
max_batch_size: 1
input [
  {
    name: "input0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 256, 256 ]
  },
  {
    name: "input1"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 256, 256 ]
  }
  
]
output [
  {
    name: "output_final"
    data_type: TYPE_FP32
    dims: [ 2, 256, 256 ]
  },
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ 2, 16, 16 ]
  },
  {
    name: "output1"
    data_type: TYPE_FP32
    dims: [ 2, 16, 16 ]
  },
  {
    name: "output2"
    data_type: TYPE_FP32
    dims: [ 2, 32, 32 ]
  },
  {
    name: "output3"
    data_type: TYPE_FP32
    dims: [ 2, 64, 64 ]
  }
]
dynamic_batching { }
