name: "changeformer_tao"
platform: "tensorrt_plan"
max_batch_size: 1
input [
  {
    name: "input0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 256, 256 ]
  },
  {
    name: "input1"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 256, 256 ]
  }
  
]
output [
  {
    name: "6938"
    data_type: TYPE_FP32
    dims: [ 2, 256, 256 ]
  },
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 2, 16, 16 ]
  },
  {
    name: "6746"
    data_type: TYPE_FP32
    dims: [ 2, 16, 16 ]
  },
  {
    name: "6833"
    data_type: TYPE_FP32
    dims: [ 2, 32, 32 ]
  },
  {
    name: "6920"
    data_type: TYPE_FP32
    dims: [ 2, 64, 64 ]
  }
]
dynamic_batching { }
