name: "foundationpose_scorer_tao"
platform: "tensorrt_plan"
max_batch_size: 252

input [
  {
    name: "inputA"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 6, 160, 160 ]
  },
  {
    name: "inputB"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 6, 160, 160 ]
  }
]
output [
  {
    name: "score_logit"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
dynamic_batching { }